import pytest, tempfile, sys, os
from day7_part1 import Day7Part1

# You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

# For example:

# .......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............

# In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

# .......S.......
# .......|.......
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............

# At that point, the original beam stops, and two new beams are emitted from the splitter:

# .......S.......
# .......|.......
# ......|^|......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............

# To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

# Analyze your manifold diagram. How many times will the beam be split?

input_text = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

def test_solve_problem0():
    problems = Day7Part1.parse_input(input_text)
    assert problems[0] == [4, 431, 623, '+']
    assert Day7Part1.solve_problem(problems[0]) == 1058

def test_solve_problem1():
    problems = Day7Part1.parse_input(input_text)
    assert problems[1] == [175, 581, 32, '*']
    assert Day7Part1.solve_problem(problems[1]) == 3253600

def test_solve_problem2():
    problems = Day7Part1.parse_input(input_text)
    assert problems[2] == [8, 248, 369, '+']
    assert Day7Part1.solve_problem(problems[2]) == 625

def test_solve_problem3():
    problems = Day7Part1.parse_input(input_text)
    assert problems[3] == [356, 24, 1, '*']
    assert Day7Part1.solve_problem(problems[3]) == 8544

def test_total_result():
    problems = Day7Part1.parse_input(input_text)
    assert Day7Part1.total_result(problems) == 3263827
