import pytest, tempfile, sys, os
from textwrap import dedent
from day7_part2 import Day7Part2

# Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

# To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

# In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ...|^.^...^....
# ...|...........
# ..|^.^...^.^...
# ..|............
# .|^...^.....^..
# .|.............
# |^.^.^.^.^...^.
# |..............

# Or, there's the timeline where the particle alternated going left and right at each splitter:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# ......^|^......
# .......|.......
# .....^|^.^.....
# ......|........
# ....^.^|..^....
# .......|.......
# ...^.^.|.^.^...
# .......|.......
# ..^...^|....^..
# .......|.......
# .^.^.^|^.^...^.
# ......|........

# Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ....^|^...^....
# .....|.........
# ...^.^|..^.^...
# ......|........
# ..^..|^.....^..
# .....|.........
# .^.^.^|^.^...^.
# ......|........

# In this example, in total, the particle ends up on 40 different timelines.

def test_total_result():
    input_text = dedent("""\
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    """)
    lines = Day7Part2.parse_input(input_text)
    assert Day7Part2.iterate_tachyon_beam(lines) == 13
    
def test_three_splitters():
    input_text = dedent("""\
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    """)
    
    lines = Day7Part2.parse_input(input_text)
    assert Day7Part2.iterate_tachyon_beam(lines) == 8

def test_three_splitters_farther_apart():
    input_text = dedent("""\
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    """)
    
    lines = Day7Part2.parse_input(input_text)
    assert Day7Part2.iterate_tachyon_beam(lines) == 13

def test_straight_beam_after_split():
    input_text = dedent("""\
    .......S.......
    ...............
    .......^.......
    ...............
    ......^........
    """)
    
    lines = Day7Part2.parse_input(input_text)
    assert Day7Part2.iterate_tachyon_beam(lines) == 3
